"""
neo4j_search.py
~~~~~~~~~~~~~~~~
Dedicated search service for Neo4j vector, fulltext, and hybrid search operations.

All Cypher queries used for index-based search are **dynamically generated by the LLM**
from the live Neo4j schema — no hardcoded query strings for the happy path.

A schema-keyed cache prevents redundant LLM calls for structurally identical queries
(e.g. the vector search Cypher only changes when the schema or top_k changes).
Safe hardcoded fallback queries are used only if the LLM is unavailable or returns
an invalid response.
"""

import re
import hashlib
import logging
from typing import List, Dict, Any, Optional, Tuple

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Fallback Cypher templates (used ONLY when LLM generation fails)
# ---------------------------------------------------------------------------

_FALLBACK_VECTOR_CYPHER = """
CALL db.index.vector.queryNodes('book_title_embedding', $top_k, $embedding)
YIELD node AS b, score
OPTIONAL MATCH (b)-[:WRITTEN_BY]->(a:Author)
OPTIONAL MATCH (b)-[:IN_CATEGORY]->(c:Category)
OPTIONAL MATCH (b)-[r:HAS_LISTING]->(s:Store)
WITH b, score,
     collect(DISTINCT a.name) AS authors,
     collect(DISTINCT c.name) AS categories,
     collect(DISTINCT {
       store: s.name,
       price: r.price,
       originalPrice: r.originalPrice,
       currency: r.currency,
       inStock: r.inStock,
       url: r.url
     }) AS listings
RETURN b.title       AS title,
       b.isbn        AS isbn,
       b.description AS description,
       b.coverImage  AS coverImage,
       authors       AS authors,
       categories    AS categories,
       listings      AS listings,
       score         AS similarity_score
ORDER BY score DESC
"""

_FALLBACK_FULLTEXT_CYPHER = """
CALL db.index.fulltext.queryNodes('book_fulltext_index', $query_text)
YIELD node AS b, score
OPTIONAL MATCH (b)-[:WRITTEN_BY]->(a:Author)
OPTIONAL MATCH (b)-[:IN_CATEGORY]->(c:Category)
OPTIONAL MATCH (b)-[r:HAS_LISTING]->(s:Store)
WITH b, score,
     collect(DISTINCT a.name) AS authors,
     collect(DISTINCT c.name) AS categories,
     collect(DISTINCT {
       store: s.name,
       price: r.price,
       originalPrice: r.originalPrice,
       currency: r.currency,
       inStock: r.inStock,
       url: r.url
     }) AS listings
RETURN b.title       AS title,
       b.isbn        AS isbn,
       b.description AS description,
       b.coverImage  AS coverImage,
       authors       AS authors,
       categories    AS categories,
       listings      AS listings,
       score         AS fulltext_score
ORDER BY score DESC
LIMIT $top_k
"""

_FALLBACK_SUBSTRING_CYPHER = """
MATCH (b:Book)
WHERE toLower(b.title) CONTAINS toLower($term)
   OR toLower(b.normalizedTitle) CONTAINS toLower($term)
OPTIONAL MATCH (b)-[:WRITTEN_BY]->(a:Author)
OPTIONAL MATCH (b)-[:IN_CATEGORY]->(c:Category)
OPTIONAL MATCH (b)-[r:HAS_LISTING]->(s:Store)
WITH b,
     collect(DISTINCT a.name) AS authors,
     collect(DISTINCT c.name) AS categories,
     collect(DISTINCT {
       store: s.name,
       price: r.price,
       originalPrice: r.originalPrice,
       currency: r.currency,
       inStock: r.inStock,
       url: r.url
     }) AS listings
RETURN b.title       AS title,
       b.isbn        AS isbn,
       b.description AS description,
       b.coverImage  AS coverImage,
       authors       AS authors,
       categories    AS categories,
       listings      AS listings
LIMIT $top_k
"""


def _schema_hash(schema: Dict[str, Any]) -> str:
    """Produces a short deterministic hash of the schema dict for cache keying."""
    serialised = str(sorted(schema.get("node_labels", {}).items()))
    return hashlib.md5(serialised.encode()).hexdigest()[:8]


class Neo4jSearchService:
    """
    Encapsulates all vector, fulltext, and hybrid search operations against Neo4j.

    Cypher queries are generated at runtime by the LLM (via ``ILLMServiceClient``)
    from the live graph schema — eliminating hardcoded query strings.
    Results are cached per (search_type, schema_hash, top_k) so repeated searches
    with the same schema don't trigger extra LLM calls.
    """

    def __init__(self, db_reader, llm_service):
        """
        Args:
            db_reader: An ``IGraphDatabaseReader`` instance (Neo4jGraphReader).
            llm_service: An ``ILLMServiceClient`` instance (GeminiLLMService).
        """
        self.db_reader = db_reader
        self.llm_service = llm_service

        # Cache: (search_type, schema_hash, top_k) -> cypher_string
        self._cypher_cache: Dict[Tuple[str, str, int], str] = {}

    # ------------------------------------------------------------------
    # Internal: LLM-based Cypher retrieval with caching
    # ------------------------------------------------------------------

    def _get_cypher(
        self,
        search_type: str,
        schema: Dict[str, Any],
        top_k: int,
        **kwargs,
    ) -> str:
        """
        Returns a Cypher query for the given search type, using a cached version
        when the schema + top_k haven't changed, or asking the LLM otherwise.
        Falls back to the hardcoded template if the LLM fails.
        """
        s_hash = _schema_hash(schema)
        cache_key = (search_type, s_hash, top_k)

        if cache_key in self._cypher_cache:
            logger.debug(
                "Using cached Cypher for %s (schema=%s, top_k=%d)", search_type, s_hash, top_k
            )
            return self._cypher_cache[cache_key]

        logger.info(
            "Generating %s search Cypher via LLM (schema=%s, top_k=%d)", search_type, s_hash, top_k
        )
        cypher = ""
        try:
            cypher = self.llm_service.generate_search_cypher(
                search_type=search_type,
                schema=schema,
                top_k=top_k,
                **kwargs,
            )
        except Exception as e:
            logger.warning("LLM generate_search_cypher(%s) raised: %s", search_type, e)

        if not cypher or len(cypher.strip()) < 10:
            logger.warning(
                "LLM returned empty/invalid Cypher for %s — using hardcoded fallback.", search_type
            )
            cypher = (
                _FALLBACK_VECTOR_CYPHER if search_type == "vector" else _FALLBACK_FULLTEXT_CYPHER
            )

        self._cypher_cache[cache_key] = cypher
        return cypher

    # ------------------------------------------------------------------
    # Public search API
    # ------------------------------------------------------------------

    def vector_search(
        self,
        query_embedding: List[float],
        top_k: int = 10,
        index_name: str = "book_title_embedding",
    ):
        """
        Performs a vector similarity search using a pre-computed query embedding.

        The Cypher query is dynamically generated from the live schema by the LLM,
        then executed against Neo4j. The result set size is controlled by ``top_k``.

        Args:
            query_embedding: Dense float vector for the user query.
            top_k: Maximum number of results to return (configurable via VECTOR_SEARCH_TOP_K).
            index_name: Name of the Neo4j vector index to query.

        Returns:
            ``CypherQueryResult`` with matched book records and similarity scores.
        """
        schema = self._fetch_schema()
        cypher = self._get_cypher("vector", schema, top_k, index_name=index_name)
        return self.db_reader.execute_read_query(
            cypher, {"top_k": top_k, "embedding": query_embedding}
        )

    def fulltext_search(
        self,
        query_text: str,
        top_k: int = 10,
        index_name: str = "book_fulltext_index",
    ):
        """
        Performs a full-text keyword search using the Lucene index in Neo4j.

        Sanitises the raw query text into significant Lucene terms before searching.
        The Cypher query is generated from the live schema by the LLM.

        Args:
            query_text: Natural-language query from the user.
            top_k: Maximum number of results (configurable via FULLTEXT_SEARCH_TOP_K).
            index_name: Name of the Neo4j fulltext index to query.

        Returns:
            ``CypherQueryResult`` with matched book records and fulltext scores.
        """
        lucene_query = self._sanitize_for_lucene(query_text)
        schema = self._fetch_schema()
        cypher = self._get_cypher("fulltext", schema, top_k, index_name=index_name)
        return self.db_reader.execute_read_query(
            cypher, {"query_text": lucene_query, "top_k": top_k}
        )

    def hybrid_search(
        self,
        query_text: str,
        query_embedding: Optional[List[float]] = None,
        top_k: int = 15,
        vector_index: str = "book_title_embedding",
        fulltext_index: str = "book_fulltext_index",
    ) -> List[Dict[str, Any]]:
        """
        Combines vector similarity search and fulltext keyword search using
        Reciprocal Rank Fusion (RRF) for result merging and deduplication.

        Falls back to a substring MATCH query if both primary searches return fewer
        than 2 results.

        Args:
            query_text: Natural-language user query (used for fulltext + substring fallback).
            query_embedding: Dense float vector for semantic search (optional).
            top_k: Maximum merged results to return (configurable via HYBRID_SEARCH_TOP_K).
            vector_index: Name of the Neo4j vector index.
            fulltext_index: Name of the Neo4j fulltext index.

        Returns:
            List of merged, deduplicated book dicts ordered by RRF score.
        """
        merged_by_key: Dict[str, Dict[str, Any]] = {}

        # 1. Full-text Keyword Search
        try:
            ft_res = self.fulltext_search(
                query_text=query_text, top_k=top_k, index_name=fulltext_index
            )
            if not ft_res.error and ft_res.records:
                for rank, record in enumerate(ft_res.records):
                    key = record.get("isbn") or record.get("title") or f"ft_{rank}"
                    rec_copy = dict(record)
                    rec_copy["_source"] = "keyword"
                    rec_copy["_ft_rank"] = rank + 1
                    merged_by_key[key] = rec_copy
        except Exception as e:
            logger.warning("Fulltext search step failed: %s", e)

        # 2. Semantic Vector Search
        if query_embedding:
            try:
                vec_res = self.vector_search(
                    query_embedding=query_embedding, top_k=top_k, index_name=vector_index
                )
                if not vec_res.error and vec_res.records:
                    for rank, record in enumerate(vec_res.records):
                        key = record.get("isbn") or record.get("title") or f"vec_{rank}"
                        if key in merged_by_key:
                            merged_by_key[key]["_source"] = "hybrid"
                            merged_by_key[key]["similarity_score"] = record.get("similarity_score")
                            merged_by_key[key]["_vec_rank"] = rank + 1
                        else:
                            rec_copy = dict(record)
                            rec_copy["_source"] = "semantic"
                            rec_copy["_vec_rank"] = rank + 1
                            merged_by_key[key] = rec_copy
            except Exception as e:
                logger.warning("Vector search step failed: %s", e)

        # 3. Fallback Substring Search if both searches returned few or 0 results
        if len(merged_by_key) < 2:
            clean_terms = [
                w for w in re.findall(r"\w+", query_text)
                if len(w) >= 3 and w.lower() not in (
                    "what", "price", "book", "books", "store", "stores",
                    "available", "show", "find", "much", "tell"
                )
            ]
            if clean_terms:
                term = clean_terms[0]
                try:
                    fb_res = self.db_reader.execute_read_query(
                        _FALLBACK_SUBSTRING_CYPHER, {"term": term, "top_k": top_k}
                    )
                    if not fb_res.error and fb_res.records:
                        for rank, record in enumerate(fb_res.records):
                            key = record.get("isbn") or record.get("title") or f"fb_{rank}"
                            if key not in merged_by_key:
                                rec_copy = dict(record)
                                rec_copy["_source"] = "substring"
                                merged_by_key[key] = rec_copy
                except Exception as e:
                    logger.warning("Fallback substring search failed: %s", e)

        # 4. Reciprocal Rank Fusion (RRF) scoring: 1 / (60 + rank)
        for item in merged_by_key.values():
            ft_rank = item.get("_ft_rank", 999)
            vec_rank = item.get("_vec_rank", 999)
            item["_rrf_score"] = (1.0 / (60.0 + ft_rank)) + (1.0 / (60.0 + vec_rank))

        sorted_results = sorted(
            merged_by_key.values(),
            key=lambda x: x.get("_rrf_score", 0.0),
            reverse=True,
        )
        return sorted_results[:top_k]

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _fetch_schema(self) -> Dict[str, Any]:
        """Fetches the live schema from the graph database reader."""
        try:
            return self.db_reader.get_live_schema()
        except Exception as e:
            logger.warning("Could not fetch live schema for search Cypher generation: %s", e)
            return {}

    @staticmethod
    def _sanitize_for_lucene(query_text: str) -> str:
        """
        Strips common stop-words and short tokens from a natural-language query
        to produce an effective Lucene search string.
        """
        _STOP_WORDS = {
            "the", "a", "an", "of", "in", "for", "to", "is", "at",
            "what", "price", "book", "books", "store", "stores",
            "available", "show", "me", "find", "how", "much", "tell",
        }
        words = [
            w for w in re.findall(r"\w+", query_text)
            if len(w) >= 2 and w.lower() not in _STOP_WORDS
        ]
        return " ".join(words) if words else query_text
